site_name: wadamczyk's space
use_directory_urls: false
theme: 
  name: material
  logo: 'assets/atom.png'
  favicon: 'assets/atom_fav.png'
  palette:
    primary: 'white'
    accent: 'blue'
  features:
    - navigation.top
    - navigation.tabs
    - toc.integrate  # This integrates TOC into the left sidebar


nav:
  - Abstract: index.md
  - "Teaching":
    - "Quantum Information Processing - Concepts 2025":
      - "Chapter 0: Introduction": qip1_2025/ch0.md
      - "Chapter 1a: Principles of Quantum Mechanics": qip1_2025/ch1a.md
      - "Chapter 1b: Toolbox": qip1_2025/ch1b.md
      - "organisation": qip1_2025/organisation.md
    - "Quantum Information Processing - Concepts 2024":
      - "Chapter 0: Introduction": qip1_2024/ch0.md
      - "Chapter 1a: Principles of Quantum Mechanics": qip1_2024/ch1a.md
      - "Chapter 1b: Toolbox": qip1_2024/ch1b.md
      - "Chapter 2a: Quantum Information Theory": qip1_2024/ch2a.md
      - "Chapter 3a: Computational Complexity": qip1_2024/ch3a.md
      - "Chapter 3b: Universal gates, Reversible irreversability, Oracle Functions": qip1_2024/ch3b.md
      - "Chapter 4a: DJ style algorithms": qip1_2024/ch4a.md
      - "Chapter 4b: Grover's algorithm": qip1_2024/ch4b.md
      - "Chapter 4c: Quantum Fourier Transform, Period Finding Algorithm": qip1_2024/ch4c.md
      - "Chapter 5: Shor's Algorithm": qip1_2024/ch5.md
      - "Chapter 6: Open Quantum Systems": qip1_2024/ch6.md
      - "Chapter 7: Quantum Error Correction": qip1_2024/ch7.md
      - "Chapter 8: Stabiliser Formalism": qip1_2024/ch8.md
  - "Random Walk":
    - "Quantum Optics":
      - "Light-Matter Interaction": random_walk/quantum_optics/rabi_frequencies.md
    - "Classical Optics":
      - "Aberation propagator": random_walk/classical_optics/aberations/aberations_propagator.md
  - "Courses":
    - "Scientific Writing Workshop": courses/scientific_writing_workshop/scienfitic_writing_workshop.md
  - "Projects":
    - "ekoAcademic":
      - "about": projects/ekoacademic/index.md
    - "Atomphys":
      - "about": projects/atomphys/index.md
    - "MUD":
      - "about": projects/mud/index.md

# Plugins (optional)
plugins:
  - search

extra_css:
  - 'extra.css'


# Markdown Extensions
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/collapse-nav.js